language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - pypy
install:
  - travis_retry sudo apt-get update -qq
  - travis_retry sudo apt-get install -qq screen
  - travis_retry sudo pip install --upgrade pip
  - travis_retry sudo pip install --user -U -e .[atlassian,flask,jinja2,logging,mongo,network,selenium,smpte2022,unittest,voluptuous]
  - travis_retry sudo pip install --user coveralls
script:
  - rm -rf pytoolbox/django* pytoolbox/rest_framework  # Not maintained so not testable ...
  - sudo python setup.py test
matrix:
  allow_failures:
    - python: 2.6
    - python: 3.2
after_success:
  coveralls
